name: Code For NL
title: Code For NL
description:
  nl: Code for NL is de Nederlandse community van mensen die samenwerken aan een open, eerlijke en inclusieve digitale overheid en samenleving.
  en: Code for NL is the Dutch community of people working together on open, fair, and inclusive digital government and society.
sass:
  style: compressed
defaulttags:
  - code
  - for
  - nl
  - civic
  - tech
defaults:
  - scope:
      path: "img"
    values:
      image: true
include: [".well-known"]
